General:
  Duration: 60
  NumberOfQuestion: 11

AdminCredential:
  Username: 'admin'
  Password: 'admin'

Questions:
  OpenQuestion:
    Basic:
      Easy: 2
      Normal: 0
      Difficult: 0
    Collection:
      Easy: 1
      Normal: 0
      Difficult: 0
    IO:
      Easy: 0
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 0
      Normal: 0
      Difficult: 0

  MultipleOptionQuestion:
    Basic:
      Easy: 2
      Normal: 0
      Difficult: 0
    Collection:
      Easy: 0
      Normal: 0
      Difficult: 0
    IO:
      Easy: 1
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 0
      Normal: 0
      Difficult: 0

  Java:
    Basic:
      Easy: 1
      Normal: 0
      Difficult: 0
    Collection:
      Easy: 0
      Normal: 0
      Difficult: 0
    IO:
      Easy: 0
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 0
      Normal: 0
      Difficult: 0

  Python:
    Basic:
      Easy: 20
      Normal: 30
