Title: "Esame Programmazione ad Oggetti"

General:
  Duration: 10
  WrongOptionQuestionPenalty: 0.5

AdminCredential:
  Username: 'admin'
  Password: 'admin'

Questions:
  OpenQuestion:
    Basic:
      Easy: 2
      Normal: 0
      Difficult: 0
    Collection:
      Easy: 1
      Normal: 0
      Difficult: 0
    IO:
      Easy: 1
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 1
      Normal: 0
      Difficult: 0

  MultipleOptionQuestion:
    Basic:
      Easy: 2
      Normal: 0
      Difficult: 0
    Collection:
      Easy: 0
      Normal: 0
      Difficult: 0
    IO:
      Easy: 1
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 0
      Normal: 0
      Difficult: 0

  Java:
    Basic:
      Easy: 1
      Normal: 0
      Difficult: 1
    Collection:
      Easy: 0
      Normal: 1
      Difficult: 0
    IO:
      Easy: 0
      Normal: 0
      Difficult: 0
    ObjectOriented:
      Easy: 0
      Normal: 0
      Difficult: 0

  Python:
    Basic:
      Easy: 2
      Normal: 1
