Title: "Esame Programmazione ad Oggetti"

General:
  Duration: 10
  WrongOptionQuestionPenalty: 0.5

AdminCredential:
  Username: 'admin'
  Password: 'admin'

Difficulty: "Easy"

Questions:
  Java-Code:
    Number: 3
    Weight: 3
  Java-Multiple:
    Number: 4
    Weight: 1
  Java-Open:
    Number: 5
    Weight: 1
  Python-Code:
    Number: 10
    Weight: 4
