Title: "Esame Programmazione ad Oggetti"

IsThisAnExam: False

General:
  Duration: 3
  WrongOptionQuestionPenalty: 0.5

AdminCredential:
  Username: 'admin'
  Password: 'admin'

Questions:
  Java-Code: 5
  Java-Multiple: 5
  Java-Open: 5
  Python-Code: 5
